# PowerShell → 显示
$global:PSKeyToDisplayName = @{
"A" = "A"
"B" = "B"
"C" = "C"
"D" = "D"
"E" = "E"
"F" = "F"
"G" = "G"
"H" = "H"
"I" = "I"
"J" = "J"
"K" = "K"
"L" = "L"
"M" = "M"
"N" = "N"
"O" = "O"
"P" = "P"
"Q" = "Q"
"R" = "R"
"S" = "S"
"T" = "T"
"U" = "U"
"V" = "V"
"W" = "W"
"X" = "X"
"Y" = "Y"
"Z" = "Z"
"D0" = "0"
"D1" = "1"
"D2" = "2"
"D3" = "3"
"D4" = "4"
"D5" = "5"
"D6" = "6"
"D7" = "7"
"D8" = "8"
"D9" = "9"
"OEM1" = ";"
"OemQuestion" = "/"
"Oemtilde" = "``"
"OemOpenBrackets" = "["
"OEM5" = "\"
"OEM6" = "]"
"OEM7" = "`'"
"OEMCOMMA" = ","
"OEMPERIOD" = "."
"OEMPLUS" = "="
"OEMMINUS" = "-"
"RETURN" = "ENTER"
"CAPITAL" = "CAPSLOCK"
"LWIN" = "LWIN"
"RWIN" = "RWIN"
"PRIOR" = "PGUP"
"NEXT" = "PGDN"
"END" = "END"
"HOME" = "HOME"
"INSERT" = "INS"
"DELETE" = "DEL"
"NUMPAD0" = "KP_0"
"NUMPAD1" = "KP_1"
"NUMPAD2" = "KP_2"
"NUMPAD3" = "KP_3"
"NUMPAD4" = "KP_4"
"NUMPAD5" = "KP_5"
"NUMPAD6" = "KP_6"
"NUMPAD7" = "KP_7"
"NUMPAD8" = "KP_8"
"NUMPAD9" = "KP_9"
"DECIMAL" = "KP_PERIOD"
"ADD" = "KP_PLUS"
"SUBTRACT" = "KP_MINUS"
"MULTIPLY" = "KP_MULTIPLY"
"DIVIDE" = "KP_SLASH"
"UP" = "UPARROW"
"DOWN" = "DOWNARROW"
"LEFT" = "LEFTARROW"
"RIGHT" = "RIGHTARROW"
"SPACE" = "SPACE"
"TAB" = "TAB"
"ESCAPE" = "ESC"
"F1" = "F1"
"F2" = "F2"
"F3" = "F3"
"F4" = "F4"
"F5" = "F5"
"F6" = "F6"
"F7" = "F7"
"F8" = "F8"
"F9" = "F9"
"F10" = "F10"
"F11" = "F11"
"F12" = "F12"
"PAUSE" = "PAUSE"
"SCROLL" = "SCROLLLOCK"
"PRINTSCREEN" = "PRINTSCREEN"

"LShiftKey" = "Left Shift"
"RShiftKey" = "Right Shift"
"LControlKey" = "Left Ctrl"
"RControlKey" = "Right Ctrl"
"LMenu" = "Left Alt"
"RMenu" = "Right Alt"
}

# 显示 → CFG
$global:DisplayNameToCfgKey = @{
"key" = "key"
"`'" = "`'"
"A" = "A"
"B" = "B"
"C" = "C"
"D" = "D"
"E" = "E"
"F" = "F"
"G" = "G"
"H" = "H"
"I" = "I"
"J" = "J"
"K" = "K"
"L" = "L"
"M" = "M"
"N" = "N"
"O" = "O"
"P" = "P"
"Q" = "Q"
"R" = "R"
"S" = "S"
"T" = "T"
"U" = "U"
"V" = "V"
"W" = "W"
"X" = "X"
"Y" = "Y"
"Z" = "Z"
"0" = "0"
"1" = "1"
"2" = "2"
"3" = "3"
"4" = "4"
"5" = "5"
"6" = "6"
"7" = "7"
"8" = "8"
"9" = "9"
";" = "SEMICOLON"
"/" = "/"
"``" = "``"
"[" = "["
"\" = "\"
"]" = "]"
"," = ","
"." = "."
"=" = "="
"-" = "-"
"ENTER" = "ENTER"
"CAPSLOCK" = "CAPSLOCK"
"LWIN" = "LWIN"
"RWIN" = "RWIN"
"PGUP" = "PGUP"
"PGDN" = "PGDN"
"END" = "END"
"HOME" = "HOME"
"INS" = "INS"
"DEL" = "DEL"
"KP_0" = "KP_INS"
"KP_1" = "KP_END"
"KP_2" = "KP_DOWNARROW"
"KP_3" = "KP_PGDN"
"KP_4" = "KP_LEFTARROW"
"KP_5" = "KP_5"
"KP_6" = "KP_RIGHTARROW"
"KP_7" = "KP_HOME"
"KP_8" = "KP_UPARROW"
"KP_9" = "KP_PGUP"
"KP_PERIOD" = "KP_DEL"
"KP_PLUS" = "KP_PLUS"
"KP_MINUS" = "KP_MINUS"
"KP_MULTIPLY" = "KP_MULTIPLY"
"KP_SLASH" = "KP_SLASH"
"UPARROW" = "UPARROW"
"DOWNARROW" = "DOWNARROW"
"LEFTARROW" = "LEFTARROW"
"RIGHTARROW" = "RIGHTARROW"
"SPACE" = "SPACE"
"TAB" = "TAB"
"ESC" = "ESCAPE"
"F1" = "F1"
"F2" = "F2"
"F3" = "F3"
"F4" = "F4"
"F5" = "F5"
"F6" = "F6"
"F7" = "F7"
"F8" = "F8"
"F9" = "F9"
"F10" = "F10"
"F11" = "F11"
"F12" = "F12"
"PAUSE" = "PAUSE"
"SCROLLLOCK" = "SCROLLLOCK"
"PRINTSCREEN" = "PRINTSCREEN"

"Left Shift" = "SHIFT"
"Right Shift" = "RSHIFT"
"Left Ctrl" = "CTRL"
"Right Ctrl" = "RCTRL"
"Left Alt" = "ALT"
"Right Alt" = "RALT"
}

function Get-DisplayNameFromPSKey {
    param (
        [System.Windows.Forms.Keys]$keyCode
    )
    $keyName = $keyCode.ToString()
    if ($global:PSKeyToDisplayName.ContainsKey($keyName)) {
        return $global:PSKeyToDisplayName[$keyName]
    }
    return $keyName
}

function Get-CfgKeyFromDisplayName {
    param (
        [string]$displayName
    )
    if ($global:DisplayNameToCfgKey.ContainsKey($displayName)) {
        return $global:DisplayNameToCfgKey[$displayName]
    }
    return $displayName
}